### ISSUE TITLE
Able to enter non-numbers into Height/Reach field during Onboarding [Safari 16.0]

### ISSUE THREAD

**Issue by Artemis-Hunt** [climbjios-sg/climbjios-app#109]
**Describe the bug**
Height/Reach field during Onboarding (and also edit profile page) are supposed to be numeric input fields. However, user is able to enter alphabets and other non-numbers (like &^*%^%). The "Next" button will also display 'Skip" if Height and/or Reach is filled with an invalid input.

Additionally, there will also be a visual glitch where the input label overlays on top of the invalid input.

The visual glitch does not occur if a purely-numerical input is given (e.g. 150, 300, 123456)

**To Reproduce**
1. Go to the second page of Onboarding (Enter Height, Reach, Gender Pronouns)
2. Enter an invalid input for Height or Reach (e.g. abcd123)
3. Unfocus the focused input field (by clicking on a blank space on the page)

**Expected behavior**
Input should only accept numbers.

**Screenshots**

When an invalid input is entered:
<img width="909" alt="image" src="https://user-images.githubusercontent.com/62279011/197371108-f01d2864-e7b7-4f86-9c7e-bf475d07c883.png">

When input field is unfocused:
<img width="909" alt="image" src="https://user-images.githubusercontent.com/62279011/197371122-f6d26192-3ba9-4626-885d-bd27ce7d8595.png">

When Height and/or Reach field is filled with invalid input:
<img width="909" alt="image" src="https://user-images.githubusercontent.com/62279011/197371152-551dcc7a-037f-4131-ae9c-1004b450cc16.png">

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.6
 - Browser: Safari 
 - Version: 16.0 (17614.1.25.9.10, 17614)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nathantew14** [comment]
I don't get the overlay issue on my MacOS Version 13.0 and Safari Version 16.1 (18614.2.9.1.12), but I am also able to enter non-number entries.

May I ask why the code for the onboarding pages are completely different from the profile update pages?

**Comment by nathantew14** [comment]
The prop `type="number"` for `RHFTextField` somehow transforms string inputs into `""`, which is then transformed to `undefined` by the `SANITIZE_EMPTY_VALUE` transform method thing, thus the string input is essentially auto erased, allowing the user to continue to the next section without the error message being raised.

If the `type="number"` prop is removed, then the input is somehow cast by something else to `'NaN'`, which is then caught by `Yup.number()`:
<img width="587" alt="Screenshot 2022-12-23 at 10 31 55 PM" src="https://user-images.githubusercontent.com/40333518/209352557-1dad8f65-ae70-4d19-b44a-8afa637305a4.png">

If the `shouldSanitizeEmptyValue` prop is removed, then the input is first transformed to `""`, then again cast to `'NaN'`:
<img width="588" alt="Screenshot 2022-12-23 at 10 33 56 PM" src="https://user-images.githubusercontent.com/40333518/209352698-1b9536f6-a603-4c2d-a595-d2afb69ef44b.png">

**Comment by nathantew14** [comment]
Possible to use Regex instead? We'd have to remove the `type = "number"` prop thought, which I see is used for:

```
onWheel={(e) => {
            if (other.type === 'number' && e.target instanceof HTMLElement) {
              e.target.blur();
            }
          }}
```
In `RHFTextField`, but I can't figure out if that is necessary or if it is even working (or what it does).

Also, I'm not yet sure if these values are stored as strings or numbers in the backend.

**Comment by nathantew14** [comment]
Actually I just remembered that the EditProfile page has no such issues with not catching non-number height and reach, and I only just noticed that the form in that page is built differently from the one in onboarding...
