### ISSUE TITLE
Show label for onboarding/edit profile input fields

### ISSUE THREAD

**Issue by Artemis-Hunt** [climbjios-sg/climbjios-app#145]
**Is your feature request related to a problem? Please describe.**
When input labels are enabled for input fields on the Edit Profile page, a visual bug occurs where the label overlays on top of the pre-filled user data (if it exists).

This is currently fixed by disabling the input labels as a workaround. However, this leads to the input boxes looking very empty & provides a less-than-optimal UX

Note that the edit profile form reuses the onboarding form components, hence input labels are disabled for onboarding as well

**Describe the solution you'd like**
Enable input labels, and fix issue that causes the UI bug.

**Describe alternatives you've considered**
The current workaround is not optimal. Input labels are important to the UX as they provide a fun and interactive design. For optional fields, it also helps to highlight that the field is optional.

**Additional context**
Bug as per screenshot below:
![telegram-cloud-photo-size-5-6251299142865367915-y](https://user-images.githubusercontent.com/62279011/197948287-bd1d50c5-2049-420f-a48c-ff46f96b4919.jpg)

**Comment by therizhao** [comment]
Fixed
