### ISSUE TITLE
User PATCH does not work correctly after refreshing access token

### ISSUE THREAD

**Issue by CrownKira** [climbjios-sg/climbjios-app#156]
**Describe the bug**

Reproduce: 
- Set access token expiry to 5s 
- Go to user profile page 
- Edit something
- Hit submit 
- Observe that the returned response does not update the user even though it says 200 OK

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by chownces** [comment]
Investigated this. Most likely due to the way the FE is replaying the request during the refresh token flow. The backend is receiving an empty body in the replayed request.

**Comment by therizhao** [comment]
This one closed?

**Comment by chownces** [comment]
Yup can close. Due to the content type header not being set correctly in the replay. So backend didnt recognise the body as json.
