### ISSUE TITLE
Build FE CI

### ISSUE THREAD

**Issue by CrownKira** [climbjios-sg/climbjios-app#19]

**Comment by therizhao** [comment]
This is a good to have that will help increase our velocity. Suggest to get this up after we done with v-beta release

**Comment by therizhao** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ClimbJios-634a05d07a1f1dfb495c0018/issues/climbjios-sg/climbjios-app/19?planning-poker) with Zenhub @Artemis-Hunt
