### ISSUE TITLE
Jio filter by open to climb together

### ISSUE THREAD

**Issue by therizhao** [climbjios-sg/climbjios-app#241]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when \[...\]

Can't filter jio by open to climb together

**Describe the solution you'd like**

Frontend add select button on Jios page to toggle Jios that are open to climb together.

Note the query string for this is alr setup in the backend

> From [SyncLinear.com](https://synclinear.com)

**Comment by albanBellenger** [comment]
Hello guys, 

I was looking at this issue for my first contribution. I was wondering about the logic and I'm probably getting this wrong so I would love to get your feedbacks. 

Today the field openToClimbTogether is a boolean so accepting only true/false. This type doesn't easily allow to have undefined value for the post search but that can be resolved with some code wrapping the value before sending it to the back-end.

I'm just wondering if this field is likely to evolve and accept more value such "Climbing with Friend only", "Gym asks the buyer to be present" and be moved to a string like the buy/sell field. I could do that type switch with this PR. 

It will help me to select the right UI control, I'm by default using the FilterSelect but if the boolean type is kept then a checkbox is probably more user friendly.

Thanks,
Alban
