### ISSUE TITLE
Hitting the enter key when entering name during onboarding reloads the page instead of going to the next page

### ISSUE THREAD

**Issue by nathantew14** [climbjios-sg/climbjios-app#250]
**Describe the bug**
Hitting the enter key when entering name during onboarding reloads the page instead of going to the next page.

**To Reproduce**
1. Go to the onboarding page
2. Enter any text in the name field
3. Press the enter key on keyboard (on desktop)
4. Page reloads instead of going to the next page

**Screenshots**
<img width="400" alt="Screenshot 2022-12-22 at 9 00 52 AM" src="https://user-images.githubusercontent.com/40333518/209032168-23a62a1a-b163-41fb-bef9-36d6d6bceb2b.png">

**Desktop (please complete the following information):**
 - OS: macOS Ventura Version 13.0
 - Browser: Safari
 - Version: 16.1

**Comment by nathantew14** [comment]
Seems like the easiest fix is to add a second hidden field: https://stackoverflow.com/questions/1370021/why-does-forms-with-single-input-field-submit-upon-pressing-enter-key-in-input

**Comment by therizhao** [comment]
@nathantew14 this is done right?

**Comment by nathantew14** [comment]
> @nathantew14 this is done right?

Should be bah, if this pr is also updated in the prod version. Idk how to check without another tele account to see the onboarding form leh 😅
