### ISSUE TITLE
Refactor Auth and Onboarding logic

### ISSUE THREAD

**Issue by CrownKira** [climbjios-sg/climbjios-app#38]
Currently, AuthProvider has several issues that might undermine maintainability and possibly cause unforeseen bugs. 
- Exposes too many low-level methods. 
Proposal: Ideally, the auth provider should abstract away the authentication method (implementation details), so it should not have methods like `storeTokenAndFetchUserData`, `loginFromSession` and `patchUserDataInBE` 
- Uses context to store states.
Proposal: all global states go to the redux store to be more consistent. 
- NewUserContext seems unnecessary since it is only there for temporary usage
Proposal: remove this. The global user state should suffice for the purpose. 

### Proposed AuthProvider's methods:
- login(): login and save the token to local storage
- logout(): logout and remove the token from local storage
- checkError(): checks the status of the error (if it is 401 or 403, remove the token)
- checkAuth(): check if the client is authenticated 
- getIdentity(): return the user data from redux store if exists. else, fetch and return user data

**Comment by therizhao** [comment]
Agree.

Point to add
- Should we just use redux persist to persist the tokens in local storage instead of doing it ourselves?
- Might want to consider how refresh token integrates with all of this

**Comment by CrownKira** [comment]
> Agree.
> 
> Point to add
> 
> * Should we just use redux persist to persist the tokens in local storage instead of doing it ourselves?
> * Might want to consider how refresh token integrates with all of this
> * Currently, if I'm not wrong, refresh token is a lil buggy (set expiry to 10s to check it out)

1. Sure. I think it is good since it can help reduce coupling with the underlying persistence method -> more extensible 
2. Let me think about it.
