### ISSUE TITLE
Fix Search Jios

### ISSUE THREAD

**Issue by therizhao** [climbjios-sg/climbjios-app#52]
**Describe the bug**
Jios dashboard displaying Closed Jios.

**To Reproduce**
1. Go to /dashboard/jios
2. See that Closed Jios are behaved

**Expected behavior**
Closed Jios should not be displayed. Backedn should not return closed jios. Or at least should provide param, for frontend to filter out. 

I think we could just go with isClosed=false by default.

**Screenshots**
<img width="677" alt="image" src="https://user-images.githubusercontent.com/24352004/195396508-dc7c4ab0-4a12-4fdc-b956-4c20372d1f96.png">

**Comment by chownces** [comment]
Docs updated
