### ISSUE TITLE
Telegram username regex

### ISSUE THREAD

**Issue by chownces** [climbjios-sg/climbjios-app#56]
**Describe the bug**
- [ ] Frontend Regex is currently incorrect.
- [ ] Backend has no validation on Telegram regex

**To Reproduce**
    <img width="492" alt="image" src="https://user-images.githubusercontent.com/53928333/195407066-c64e0286-3c4b-4b27-a5b4-830d4c074cbe.png">

**Comment by therizhao** [comment]
With the new OAuth

@chownces Can be closed?

**Comment by chownces** [comment]
> With the new OAuth
> 
> @chownces Can be closed?

Nope, we can't close this unless we are shifting to 100% Telegram flow. Even then, some users might not have a Telegram username, as it is optional to have one (but then they wouldn't be able to use our app since we rely on the t.me links)

**Comment by therizhao** [comment]
@Artemis-Hunt Update this

Lowercase and one string
