### ISSUE TITLE
Telegram OAuth Flow

### ISSUE THREAD

**Issue by chownces** [climbjios-sg/climbjios-app#57]
**Is your feature request related to a problem? Please describe.**
Let's shift over to the Telegram OAuth flow:
- Existing ClimbJios users are already on Telegram
- Ensures correctness of Telegram username
- Allows us to authorize a bot to PM users (if necessary in the future)

**Comment by therizhao** [comment]
I'm reconsidering if we need this for v1.

**Comment by therizhao** [comment]
To be discussed in kickoff.

**Comment by chownces** [comment]
Closed by #60
