### ISSUE TITLE
Telegram users without usernames do not have t.me links

### ISSUE THREAD

**Issue by chownces** [climbjios-sg/climbjios-app#63]
**Describe the bug**

Telegram usernames are optional. Without usernames, we can't access the user's profile via the t.me links. This means that our app flow breaks for such users. We should provide some way of informing the user that this is an issue, and the steps to rectify it (e.g. how to create a username)

**Comment by therizhao** [comment]
Would argue this isn't urgent. Since most ppl with Tele has usernames.

More like an edge case.
