### ISSUE TITLE
Disable Google Login

### ISSUE THREAD

**Issue by therizhao** [climbjios-sg/climbjios-app#86]

**Comment by therizhao** [comment]
Comment out frontend

**Comment by chownces** [comment]
Rationale:
- Telegram OAuth flow ensures all usernames are validated
- Telegram OAuth flow allows us to authorize a Telegram bot to message users. This opens up opportunities for:
    - Notification services via our bot
    - Other Telegram bot features in the future
- Our initial target group are all Telegram users (ClimbJios Telegram group)
